# Project information
site_name: LangFlow
site_description: LangFlow is a GUI for LangChain, designed with react-flow to provide an effortless way to experiment and prototype flows with drag-and-drop components and a chat box.
site_url: https://github.com/logspace-ai/langflow

# Repository
repo_name: logspace-ai/langflow
repo_url: https://github.com/logspace-ai/langflow

# Configuration
theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.prune
    - navigation.sections
    # - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/chain.png
  favicon: img/chain.png

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom

# Page tree
nav:
  - What is LangFlow?: index.md
  - Getting Started:
    - Installation: installation.md
    # - Run Locally: locally.md
    # - Run Docker: local-development.md
    - Creating Flows: create-flows.md
    - Hugging Face Spaces: hugging-face-spaces.md
    - Guidelines: guidelines.md
  - Examples:
    - How to Upload Examples?: langflow-examples.md
    - Memories:
      - Conversation Summary Memory: conversation-summary-memory.md
      - Conversation Buffer Memory: conversation-buffer-memory.md  
    - Chains:
      - LLMChain: llmchain.md
      - Series Character Chain: series-character-chain.md
      - MidJourney Prompt Chain: midjourney-prompt-chain.md
      - Time Travel Guide Chain: time-travel-guide-chain.md  
    - Agents:
      - Vector Store Agent: vectorstore-agent.md
      - Multiple Vectorstores: multiple-vectorstores.md
      - JSON Agent: json-agent.md  
    - Tools:
      - PAL-MATH: tool-pal-math.md
      - Serp API: serp-api.md
      - News API: news-api.md
    - Document Loaders:
      - PyPDFLoader: py-pdf-loader.md
      - CSVLoader: csv-loader.md
  - GCP Deployment: 
    - GCP_DEPLOYMENT.md
  - Release Notes:
    - releases.md
  - Contributing:
    - How to contribute?: contribute.md
    - GitHub Issues: github-issues.md
    - Community: community.md    


# Customization
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/logspace-ai/langflow
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/logspace_ai
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/logspace-ai

# Extensions
markdown_extensions:
  - lightgallery:
      show_description_in_lightgallery: true
      show_description_as_inline_caption: false
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - markdown.extensions.codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra:
  generator: false
  extra_css:
  - css/termynal.css
  - css/custom.css
  extra_javascript:
  - js/termynal.js
  - js/custom.js

copyright: |
  &copy; 2023 <a href="https://github.com/logspace-ai"  target="_blank" rel="noopener">Logspace</a>

extra_css:
  - stylesheets/custom.css

extra_javascript:
  - javascripts/mendablesearch.js
